version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"

  auth-service:
    build: ./auth
    ports:
      - "${AUTH_SERVICE_PORT}:3000"
    environment:
      - MONGO_URI=${MONGO_URI}/auth
      - RABBITMQ_URL=${RABBITMQ_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
      - rabbitmq

  music-service:
    build: ./music
    ports:
      - "${MUSIC_SERVICE_PORT}:3000"
    environment:
      - MONGO_URI=${MONGO_URI}/music
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongodb

  notification-service:
    build: ./notification
    environment:
      - MONGO_URI=${MONGO_URI}/notifications
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - mongodb
      - rabbitmq

  tunepal-service:
    build: ./TunePal
    ports:
      - "${TUNEPAL_SERVICE_PORT}:3005"
    environment:
      - MONGO_URI=${MONGO_URI}/tunepal
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongodb

  artist-frontend:
    build: ./Artist
    ports:
      - "${ARTIST_FRONTEND_PORT}:80"
    depends_on:
      - auth-service
      - music-service

  user-frontend:
    build: ./Users
    ports:
      - "${USER_FRONTEND_PORT}:80"
    depends_on:
      - auth-service
      - music-service
      - tunepal-service

volumes:
  mongodb_data:
